21e00595|2024-02-23 11:14:32-0500|HOST_CONNECT|172.16.0.2|
ssh: connect to host 172.16.0.2 port 22: Operation timed out
21e00595|2024-02-23 11:14:42-0500|HOST_CONNECT_ERROR|172.16.0.2|255
cd4f00ca|2024-02-23 11:14:42-0500|HOST_CONNECT|172.16.0.4|
Warning: Permanently added '172.16.0.4' (ED25519) to the list of known hosts.
cd4f00ca|2024-02-23 11:14:42-0500|EXEC_BEGIN|sysctl|
cd4f00ca|2024-02-23 11:14:42-0500|EXEC_END|sysctl|0
cd4f00ca|2024-02-23 11:14:42-0500|EXEC_BEGIN|packages|
cd4f00ca|2024-02-23 11:14:43-0500|EXEC_END|packages|0
cd4f00ca|2024-02-23 11:14:43-0500|EXEC_BEGIN|directories|
cd4f00ca|2024-02-23 11:14:43-0500|EXEC_END|directories|0
cd4f00ca|2024-02-23 11:14:43-0500|EXEC_BEGIN|init_node|
11:14:43 83914 WARN  No encryption is used for network traffic! This allows an attacker on the network to read all replication data.
11:14:43 83914 WARN  Using --ssl-self-signed instead of --no-ssl is recommend to achieve more security with the same ease of deployment.
11:14:43 83914 WARN  See https://www.postgresql.org/docs/current/libpq-ssl.html for details on how to improve
11:14:43 83914 INFO  Using default --ssl-mode "prefer"
11:14:43 83914 INFO  Connecting to 172.16.0.1 (port 5432)
11:14:43 83914 WARN  Failed to resolve hostname from address "172.16.0.4": name or service is not known
11:14:43 83914 INFO  Using local IP address "172.16.0.4" as the --hostname.
11:14:43 83914 INFO  Started pg_autoctl postgres service with pid 59416
11:14:43 59416 INFO   /usr/local/bin/pg_autoctl do service postgres --pgdata /var/postgresql/data -v
11:14:43 83914 INFO  Started pg_autoctl node-init service with pid 49740
11:14:43 49740 INFO  Registered node 1 "node_1" (172.16.0.4:5432) in formation "default", group 0, state "single"
11:14:43 49740 INFO  Writing keeper state file at "/var/postgresql/.local/share/pg_autoctl/var/postgresql/data/pg_autoctl.state"
11:14:43 49740 INFO  Writing keeper init state file at "/var/postgresql/.local/share/pg_autoctl/var/postgresql/data/pg_autoctl.init"
11:14:43 49740 INFO  Successfully registered as "single" to the monitor.
11:14:43 49740 INFO  FSM transition from "init" to "single": Start as a single node
11:14:43 49740 INFO  Initialising postgres as a primary
11:14:43 49740 INFO  Initialising a PostgreSQL cluster at "/var/postgresql/data"
11:14:43 49740 INFO  /usr/local/bin/pg_ctl initdb -s -D /var/postgresql/data --option '--auth=trust'
11:14:44 59416 ERROR pg_controldata: error: could not read file "/var/postgresql/data/global/pg_control": read 0 of 296
11:14:44 59416 ERROR Failed to run "/usr/local/bin/pg_controldata" on "/var/postgresql/data", see above for details
11:14:46 95486 INFO   /usr/local/bin/postgres -D /var/postgresql/data -p 5432 -h *
11:14:46 59416 INFO  Postgres is now serving PGDATA "/var/postgresql/data" on port 5432 with pid 95486
11:14:46 49740 INFO  The user "_postgresql" already exists, skipping.
11:14:46 49740 INFO  CREATE USER _postgresql
11:14:46 49740 INFO  CREATE DATABASE postgres;
11:14:46 49740 INFO  The database "postgres" already exists, skipping.
11:14:46 49740 INFO  CREATE EXTENSION pg_stat_statements;
11:14:46 49740 INFO  Disabling synchronous replication
11:14:46 49740 INFO  Reloading Postgres configuration and HBA rules
11:14:46 49740 INFO  Reloading Postgres configuration and HBA rules
11:14:46 49740 INFO  Transition complete: current state is now "single"
11:14:46 49740 INFO  keeper has been successfully initialized.
11:14:46 83914 WARN  pg_autoctl service node-init exited with exit status 0
11:14:46 59416 INFO  Postgres controller service received signal SIGTERM, terminating
11:14:46 59416 INFO  Stopping pg_autoctl postgres service
11:14:46 59416 INFO  /usr/local/bin/pg_ctl --pgdata /var/postgresql/data --wait stop --mode fast
11:14:47 83914 INFO  Stop pg_autoctl
cd4f00ca|2024-02-23 11:14:47-0500|EXEC_END|init_node|0
cd4f00ca|2024-02-23 11:14:47-0500|EXEC_BEGIN|pg_hba|
--- /var/postgresql/data/pg_hba.conf	Fri Feb 23 11:14:46 2024
+++ rsub_uqBp0Ogu	Fri Feb 23 11:14:47 2024
@@ -99,2 +99,6 @@
 host "postgres" "_postgresql" 172.16.0.4/32 trust # Auto-generated by pg_auto_failover
 host all "pgautofailover_monitor" 172.16.0.1/32 trust # Auto-generated by pg_auto_failover
+# start managed block
+host    sidecomment     sidecomment    172.16.0.0/24    md5
+host    all             eradman        172.16.0.0/24    md5
+# end managed block
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
cd4f00ca|2024-02-23 11:14:47-0500|EXEC_END|pg_hba|2
cd4f00ca|2024-02-23 11:14:47-0500|EXEC_BEGIN|rc.d|
pg_autoctl(ok)
>> ssh -t 172.16.0.4 doas -u _postgresql tmux attach
cd4f00ca|2024-02-23 11:14:47-0500|EXEC_END|rc.d|0
cd4f00ca|2024-02-23 11:14:47-0500|HOST_DISCONNECT|172.16.0.4|0
